language: python

cache: pip

python:
    - "3.6"
    - "3.7"


matrix:
    fast_finish: false
    allow_failures:
        - python: "3.7"  # Travis CI not supporting 3.7 yet


install:
    - pip install -r requirements.txt
    - pip install coveralls


# command to run tests
script:
    - pytest

after_success: coveralls
