language: python

python:
    - "3.6"


install:
    - pip install -r requirements.txt
    - pip install coveralls pytest-cov


# command to run tests
script:
    - pytest --cov

after_success: coveralls
